export const WIDGET_URI = "ui://agentic-travel/trip-v2.html";

export const widgetHtml = String.raw`<!doctype html>
<html lang="ja">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <style>
    :root{color-scheme:light dark;--text:#202123;--muted:#6b6f76;--line:#e5e5e5;--surface:#fff;--soft:#f7f7f7;--accent:#3157e8;--accent-soft:#eef1ff;--good:#087d50;--good-soft:#eaf7f1;--warn:#9a5b08;--warn-soft:#fff6e5;--bad:#bd2c2c;--bad-soft:#fff0f0}
    *{box-sizing:border-box}html,body{margin:0;background:transparent}body{color:var(--text);font:14px/1.45 -apple-system,BlinkMacSystemFont,"Segoe UI","Hiragino Sans","Yu Gothic",sans-serif}button,input{font:inherit}button{cursor:pointer}.card{width:100%;padding:16px;display:grid;gap:14px;background:var(--surface)}
    h2,h3,p{margin:0}h2{font-size:17px;line-height:1.35}h3{font-size:14px}.muted{color:var(--muted);font-size:12px}.top,.row,.summary,.actions{display:flex;align-items:center;justify-content:space-between;gap:12px}.top{align-items:flex-start}.badge{padding:3px 7px;border-radius:999px;color:var(--muted);background:var(--soft);font-size:10px;font-weight:650;white-space:nowrap}.badge.good{color:var(--good);background:var(--good-soft)}.badge.warn{color:var(--warn);background:var(--warn-soft)}.badge.bad{color:var(--bad);background:var(--bad-soft)}
    .rows{display:grid;border-top:1px solid var(--line)}.row{min-height:40px;padding:9px 0;border-bottom:1px solid var(--line)}.row strong{font-size:13px;text-align:right}.amount{font-size:20px;font-weight:720;white-space:nowrap}.section{display:grid;gap:7px}.section-title{display:flex;align-items:center;gap:7px;color:var(--muted);font-size:11px;font-weight:650}.count{display:inline-grid;min-width:18px;height:18px;padding:0 5px;place-items:center;border-radius:999px;background:var(--soft)}
    .choice{position:relative;display:grid;grid-template-columns:20px 1fr auto;gap:9px;align-items:center;padding:10px;border:1px solid var(--line);border-radius:11px}.choice:has(input:checked){border-color:var(--accent);background:var(--accent-soft)}.choice input{width:16px;height:16px;margin:0;accent-color:var(--accent)}.choice-copy{min-width:0}.choice-copy strong,.choice-copy small{display:block}.choice-copy strong{font-size:13px}.choice-copy small{margin-top:2px;color:var(--muted);font-size:11px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.choice-price{text-align:right;font-weight:650;white-space:nowrap}.tag{display:inline-block;margin-left:5px;padding:1px 5px;border-radius:5px;color:var(--accent);background:var(--accent-soft);font-size:9px;font-weight:700}
    .summary{padding:11px 12px;border-radius:10px;background:var(--soft)}.summary.over{color:var(--bad);background:var(--bad-soft)}.approval-item{display:grid;grid-template-columns:1fr auto;gap:3px 12px;padding:10px 0;border-bottom:1px solid var(--line)}.approval-item:last-child{border-bottom:0}.approval-item small{grid-column:1/3;color:var(--muted)}.reason{color:var(--warn)!important}.notice{padding:11px 12px;border-radius:10px;background:var(--warn-soft);color:var(--warn);font-size:12px}.notice.bad{color:var(--bad);background:var(--bad-soft)}
    .actions{justify-content:flex-start}.primary,.secondary{min-height:38px;padding:9px 13px;border-radius:9px;font-weight:650}.primary{border:1px solid var(--accent);color:white;background:var(--accent)}.secondary{border:1px solid var(--line);color:var(--text);background:var(--surface)}button:disabled{opacity:.45;cursor:not-allowed}.foot{color:var(--muted);font-size:11px}.timeline{display:grid}.event{position:relative;padding:8px 0 8px 19px;border-left:1px solid var(--line);margin-left:5px}.event:before{content:"";position:absolute;left:-4px;top:14px;width:7px;height:7px;border-radius:50%;background:var(--good)}.event.bad:before{background:var(--bad)}.event strong,.event small{display:block}.event small{color:var(--muted)}.loading{opacity:.55;pointer-events:none}
    @media(prefers-color-scheme:dark){:root{--text:#ececec;--muted:#a6a6a6;--line:#3d3d3d;--surface:#212121;--soft:#2f2f2f;--accent:#7690ff;--accent-soft:#29304c;--good:#65c79c;--good-soft:#203a31;--warn:#efb45f;--warn-soft:#49371f;--bad:#ff8585;--bad-soft:#482626}}
    @media(max-width:460px){.card{padding:14px}.choice{grid-template-columns:20px 1fr}.choice-price{grid-column:2;text-align:left}.actions{display:grid;grid-template-columns:1fr}.primary,.secondary{width:100%}}
  </style>
</head>
<body>
  <main id="app"><section class="card"><p class="muted">ChatGPTから旅行の相談を始めると、ここに操作カードが表示されます。</p></section></main>
  <script>
    const app=document.getElementById('app');let data=null;let requestId=1;const pending=new Map();
    const yen=value=>new Intl.NumberFormat('ja-JP',{style:'currency',currency:'JPY',maximumFractionDigits:0}).format(value||0);
    const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
    const post=message=>window.parent.postMessage(message,'*');
    function rpc(method,params){return new Promise((resolve,reject)=>{const id=requestId++;pending.set(id,{resolve,reject});post({jsonrpc:'2.0',id,method,params});setTimeout(()=>{if(pending.has(id)){pending.delete(id);reject(new Error('host unavailable'))}},5000)})}
    async function connect(){if(window.parent===window)return;try{await rpc('ui/initialize',{appInfo:{name:'agentic-travel-ui',version:'0.2.0'},appCapabilities:{},protocolVersion:'2026-01-26'});post({jsonrpc:'2.0',method:'ui/notifications/initialized'})}catch(_){}}
    window.addEventListener('message',event=>{if(event.source!==window.parent)return;const message=event.data;if(!message||message.jsonrpc!=='2.0')return;if(message.id!==undefined&&pending.has(message.id)){const waiter=pending.get(message.id);pending.delete(message.id);message.error?waiter.reject(message.error):waiter.resolve(message.result)}if(message.method==='ui/notifications/tool-result')update(message.params?.structuredContent)});
    async function callTool(name,args){app.classList.add('loading');try{const result=await rpc('tools/call',{name,arguments:args});if(result?.structuredContent)update(result.structuredContent)}catch(error){showError(error?.message||'操作を完了できませんでした')}finally{app.classList.remove('loading')}}
    function update(next){if(!next)return;data=next;render();notifySize()}
    function notifySize(){requestAnimationFrame(()=>post({jsonrpc:'2.0',method:'ui/notifications/size-changed',params:{width:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight}}))}
    function showError(message){app.insertAdjacentHTML('beforeend','<p class="notice bad">'+esc(message)+'</p>');notifySize()}
    function row(label,value){return '<div class="row"><span class="muted">'+esc(label)+'</span><strong>'+esc(value)+'</strong></div>'}
    function actions(primary,secondary=''){return '<div class="actions">'+primary+secondary+'</div>'}
    function renderMandate(){return '<section class="card"><div class="top"><div><h2>'+esc(data.trip.destination)+'旅行の支払い条件</h2><p class="muted">'+esc(data.trip.dates)+'・'+data.trip.travelers+'名</p></div><span class="badge">CARD SANDBOX</span></div><div class="rows">'+row('総予算',yen(data.trip.budget))+row('自動決済','1件 '+yen(data.trip.autoPayLimit)+'まで')+row('必ず確認','上限超過・取消不可・価格5%以上上昇')+'</div>'+actions('<button class="primary" data-action="search">候補を探す</button>')+'<p class="foot">条件を変えたい場合は、そのままChatGPTに話しかけてください。</p></section>'}
    const categoryLabel={lodging:'宿（1件選択）',activity:'体験（複数選択可）',food:'夕食（任意）'};
    function choice(item){const type=item.category==='activity'?'checkbox':'radio';const name=item.category==='lodging'?'lodging':item.category==='food'?'food':'activity';const checked=data.selectedItemIds.includes(item.id)?' checked':'';return '<label class="choice"><input type="'+type+'" name="'+name+'" data-item="'+esc(item.id)+'"'+checked+'><span class="choice-copy"><strong>'+esc(item.name)+(item.recommended?'<span class="tag">おすすめ</span>':'')+'</strong><small>'+esc(item.reason)+'・'+(item.cancellable?'変更可':'取消不可')+'</small></span><span class="choice-price">'+yen(item.price)+'</span></label>'}
    function renderInventory(){const groups=['lodging','activity','food'].map(category=>{const items=data.inventory.filter(item=>item.category===category);const hasFood=data.selectedItemIds.some(id=>items.some(item=>item.id===id));const none=category==='food'?'<label class="choice"><input type="radio" name="food" data-none-food'+(hasFood?'':' checked')+'><span class="choice-copy"><strong>夕食は予約しない</strong><small>現地で決める</small></span><span class="choice-price">¥0</span></label>':'';return '<div class="section"><div class="section-title">'+categoryLabel[category]+' <span class="count">'+items.length+'</span></div>'+items.map(choice).join('')+none+'</div>'}).join('');return '<section class="card"><div class="top"><div><h2>好きな組み合わせを選んでください</h2><p class="muted">おすすめは選択済みです。宿・体験・夕食を個別に変更できます。</p></div><span class="badge">SIMULATED</span></div>'+groups+'<div class="summary" id="selection-summary"><span>選択中</span><strong id="selection-total"></strong></div>'+actions('<button class="primary" id="review" data-action="review">この組み合わせを確認</button>')+'<p class="foot">「駅より温泉重視」「夕食はいらない」など、会話からの絞り込みもできます。</p></section>'}
    function approvalReason(item){const reasons=[];if(item.price>data.trip.autoPayLimit)reasons.push('自動決済上限を超過');if(!item.cancellable)reasons.push('キャンセル不可');return reasons.length?reasons.join('・'):'設定した範囲内で自動確定'}
    function renderApproval(){const list=data.selectedItems.map(item=>'<div class="approval-item"><strong>'+esc(item.name)+'</strong><strong>'+yen(item.price)+'</strong><small class="'+(approvalReason(item).includes('自動確定')?'':'reason')+'">'+approvalReason(item)+'</small></div>').join('');return '<section class="card"><div class="top"><div><h2>予約と支払いの最終確認</h2><p class="muted">選んだ内容だけを処理します</p></div><span class="badge warn">承認待ち</span></div><div>'+list+'</div><div class="summary"><span>合計</span><strong class="amount">'+yen(data.selectedTotal)+'</strong></div><div class="notice">上限超過・取消不可の商品が含まれるため、ここで明示的な承認が必要です。</div>'+actions('<button class="primary" data-action="execute">'+yen(data.selectedTotal)+'を承認</button>','<button class="secondary" data-action="search">選び直す</button>')+'<p class="foot">実課金は行われません。カードSandboxで処理します。</p></section>'}
    function renderException(){const ex=data.exception;return '<section class="card"><div class="top"><div><h2>ホテル料金が変わったため停止しました</h2><p class="muted">承認済み条件から '+ex.deltaPercent+'% 上昇</p></div><span class="badge bad">決済前に停止</span></div><div class="rows">'+row(ex.item.name,yen(ex.previousPrice)+' → '+yen(ex.currentPrice))+row('変更後の合計',yen(data.selectedTotal))+'</div><div class="notice bad">AIは変更後の金額を勝手に支払いません。</div><div class="section"><div class="section-title">代替候補</div><div class="choice"><span>↳</span><span class="choice-copy"><strong>'+esc(ex.alternative.name)+'</strong><small>'+esc(ex.alternative.reason)+'・変更可</small></span><span class="choice-price">'+yen(ex.alternative.price)+'</span></div></div>'+actions('<button class="primary" data-action="alternative">代替ホテルに変更</button>','<button class="secondary" data-action="reapprove">'+yen(ex.currentPrice)+'で再承認</button>')+'</section>'}
    function renderAudit(){const denied=data.status==='denied';const list=data.audit.slice(-5).map(event=>'<div class="event '+(event.type==='denied'||event.type==='blocked'?'bad':'')+'"><strong>'+esc(event.label)+'</strong><small>'+esc(event.detail)+'</small></div>').join('');return '<section class="card"><div class="top"><div><h2>'+(denied?'支払いは実行されませんでした':'予約が完了しました')+'</h2><p class="muted">'+(denied?'ポリシーが資金移動前に拒否しました':'選択した内容をカードSandboxで処理しました')+'</p></div><span class="badge '+(denied?'bad':'good')+'">'+(denied?'DENIED':'CONFIRMED')+'</span></div><div class="summary"><span>'+(denied?'移動額':'支払額')+'</span><strong class="amount">'+yen(data.paidAmount)+'</strong></div><div class="timeline">'+list+'</div>'+row('Payment ID',data.paymentId||'発行なし')+'</section>'}
    function render(){if(!data)return;app.innerHTML=data.view==='mandate'?renderMandate():data.view==='inventory'?renderInventory():data.view==='approval'?renderApproval():data.view==='exception'?renderException():renderAudit();bind();if(data.view==='inventory')updateSelectionSummary()}
    function selectedIds(){return [...document.querySelectorAll('[data-item]:checked')].map(input=>input.dataset.item)}
    function updateSelectionSummary(){const ids=selectedIds();const total=data.inventory.filter(item=>ids.includes(item.id)).reduce((sum,item)=>sum+item.price,0);const hasHotel=data.inventory.some(item=>item.category==='lodging'&&ids.includes(item.id));const summary=document.getElementById('selection-summary');const totalNode=document.getElementById('selection-total');const review=document.getElementById('review');if(totalNode)totalNode.textContent=yen(total)+' / '+yen(data.trip.budget);const invalid=!hasHotel||total>data.trip.budget;if(summary)summary.classList.toggle('over',invalid);if(review)review.disabled=invalid;notifySize()}
    function bind(){document.querySelectorAll('[data-item],[data-none-food]').forEach(input=>input.addEventListener('change',updateSelectionSummary));document.querySelectorAll('[data-action]').forEach(button=>button.addEventListener('click',()=>handleAction(button.dataset.action)))}
    function handleAction(action){if(action==='search')return callTool('search_trip_inventory',{tripId:data.tripId});if(action==='review')return callTool('review_trip_selection',{tripId:data.tripId,itemIds:selectedIds()});if(action==='execute')return callTool('confirm_and_pay',{tripId:data.tripId});if(action==='reapprove'||action==='alternative')return callTool('resolve_trip_exception',{tripId:data.tripId,action})}
    connect();notifySize();
  </script>
</body>
</html>`;
